Address descriptors
googlemaps/google-maps-services-go pull request #295
Opened 2024-02-16 19:11 UTC by tcliff111

Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ x] Ensure the tests and linter pass
- [x ] Code coverage does not decrease (if any source code was changed)
- [ x] Appropriate docs were updated (if necessary)

Fixes #294 🦕

2024-02-29 17:35 UTC, wangela requested changes
- Let's update the README "Usage" section with either a demonstration of Geocoding or a pointer to see examples by examining tests.
- Does https://github.com/googlemaps/google-maps-services-go/blob/master/examples/geocoding/cmdline/main.go need to be updated as well?

2024-04-08 21:46 UTC, tcliff111 commented
> * Let's update the README "Usage" section with either a demonstration of Geocoding or a pointer to see examples by examining tests.
> * Does https://github.com/googlemaps/google-maps-services-go/blob/master/examples/geocoding/cmdline/main.go need to be updated as well?

Just updated the README and also updated the main.go file.

2024-07-16 17:42 UTC, wangela requested changes

2024-07-16 17:42 UTC, wangela commented on README.md
> +Sample usage of the Geocoding API with an API key to get an [Address Descriptor](https://mapsplatform.google.com/demos/address-descriptors/):
https://developers.google.com/maps/documentation/geocoding/address-descriptors/requests-address-descriptors might be a more useful destination for the hyperlink

2024-07-16 17:45 UTC, wangela approved these changes

2024-07-16 17:47 UTC, merged

2026-04-29 17:25 UTC, pachecocordovamoiseseduardo-byte approved these changes